name: Build and Deploy to aws-lambda

on:
  push:
    branches:
    - master

jobs:
  build:
    name: 'Build'
    runs-on: ubuntu-latest
    environment: production

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'

      - name: Installing packages
        run: npm install

      - name: Building Function
        run: npx ncc build index.ts

  deploy:
    name: 'Deploy, aws lambda' 
    runs-on: ubuntu-latest
    needs: build
    environment: 'Production'

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Creating ZIP
        run: zip -j deploy.zip ./dist/*

      - name: Deploying
        run: aws lambda update-function-code --function-name=${{ secrets.lambda_function_name }} --zip-file=fileb://deploy.zip