name: Build and Deploy to aws-lambda

on:
  push:
    branches:
    - master


jobs:
  Deploy:
    name: 'Installing, Building, and Deploying Function'
    runs-on: ubuntu-latest
    environment: production

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: "Installing, Building, and Deploying Function"
        run: |
          cd lambda
          pwd
          for fun in test-fun-1 test-fun-2 ; do
            echo ${fun}
            cd ${fun}
            
            if [[ -f "package.json" ]]; then
              echo "Installing packages"
              npm i
              
              if [[ -f "index.ts" ]]; then
                echo "Build Function"
                npx ncc build index.ts

                if [[ -d "dist" ]]; then
                  echo "Creating Zip"
                  zip -j deploy.zip ./dist/*

                  echo "Deploying Lambda"
                  aws lambda update-function-code --function-name=${fun} --zip-file=fileb://deploy.zip

                  echo "${fun} Deployed."
                fi
              fi
            fi

            cd ..
          done