name: Build and Deploy to aws-lambda

on:
  push:
    branches:
    - master


jobs:
  Deploy:
    name: 'Installing, Building, and Deploying Function'
    runs-on: ubuntu-latest
    environment: production

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'

      - name: Installing packages
        run: |
          cd lambda
          pwd
          for fun in test-fun-1 test-fun-2 ; do
            echo ${fun}
            cd ${fun}
            
            if [[ -f "package.json" ]]; then
              echo "Installing packages"
              npm i
              
              if [[ -f "index.ts" ]]; then
                npx ncc build index.ts

                dir
              fi
            fi

            cd ..
          done